### ISSUE TITLE
 ErrorException in Image.php line 101

### ISSUE THREAD

**Issue by aerni90** [aryehraber/statamic-responsive-img#1]
I followed the instructions on how to use this addon, but can't get it to work. It throws the following error. [statamic-2018-09-03.log](https://github.com/aryehraber/statamic-responsive-img/files/2345579/statamic-2018-09-03.log)

**Comment by aryehraber** [comment]
Thanks for the issue report! 

The error looks similar to what I was hitting during development, and it was solved after turning on [image caching](https://docs.statamic.com/tags/glide#serving-cached-images). Can you confirm this setting it on, and that the physical image exists at the path in the log?

**Comment by aerni90** [comment]
I can confirm that image caching is turned on. 

**assets.yaml**
```image_manipulation_cached: true
image_manipulation_route: /images
image_manipulation_cached_path: public/images```


However the image path seems to be wrong. I'm running Statamic above webroot. Maybe that's causing the problem. Lo

**Path in the log**
```/Users/michael/Valet/baerenmatte/statamic/../images/containers/images/./027.jpg/21134e042559c226ed49cd6cff67bad3.jpg```

**Actual path of the image**
```/Users/michael/Valet/baerenmatte/public/images/containers/images/027.jpg/21134e042559c226ed49cd6cff67bad3.jpg```

**Comment by aryehraber** [comment]
Aha! I didn't test above webroot, so that could very well be the issue. I don't have a project setup locally above webroot. Can you please test the follow change:

In `site/addons/ResponsiveImg/Image.php` line 101 replace the line with:
```php
return base64_encode(file_get_contents(webroot_path($imageUrl)));
```

**Comment by aerni90** [comment]
That fixed it! Thanks!

**Comment by aryehraber** [comment]
Awesome, thanks for testing and getting back to me so quickly. I'll have an official release out later today!

**Comment by aryehraber** [comment]
Updated: https://statamic.com/marketplace/addons/responsive-img/changelog

Thanks again!
