### ISSUE TITLE
Parentheses not allowed

### ISSUE THREAD

**Issue by StylishUnicorn** [aryehraber/statamic-responsive-img#10]
If you select an image with parentheses, it throws the following error:

`Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: file_get_contents(/home/[webserver]/public_html/img/containers/main/./abstract-ai-art-373543-%281%29.jpg/cc2541df24434bbae9bae97dd2c96867.jpg): failed to open stream: No such file or directory (View: /home/[webserver]/public_html/site/addons/ResponsiveImg/resources/views/img.blade.php)`

**Comment by aryehraber** [comment]
From the error message it seems that the image can't be found. Can you confirm you followed the installation instructions in the docs? Specifically, are you sure you are [Serving Cached Images Directly](
https://docs.statamic.com/tags/glide#serving-cached-images)?

**Comment by StylishUnicorn** [comment]
Hi, yeah I followed everything and am serving cached images directly. The file is also 100% on the server. Every other image is working except the ones with parentheses in them.

**Comment by StylishUnicorn** [comment]
Uploaded via Statamic. Thanks for taking a look :)

**Comment by aryehraber** [comment]
Fixed in latest release!
