### ISSUE TITLE
Can this be used with theme images

### ISSUE THREAD

**Issue by roarkmccolgan** [aryehraber/statamic-responsive-img#20]
Hi,

Great add on, thank you!

Is there a way we can use this with theme images?

Thanks

**Comment by aryehraber** [comment]
Off the top of my head, no I don't think you can atm.

As a potential workaround, I'd simply use front-matter at the top of a template file for the image URL/ID and then use as you would normally, example from README:

```
---
banner: /assets/img/hero-banner.jpg
---
<div>
  {{ responsive_img:banner attr="class:w-full" }}
</div>
```

**Comment by roarkmccolgan** [comment]
Great thank you!
