### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kodeine** [aryehraber/statamic-responsive-img#6]
i am getting the following error,
```
<img src="{{ glide:photo }}" alt="{{ caption }}"> --> works
{{ responsive_img:photo attr="class:w-full" }} ---> error
```
<img width="1009" alt="screen shot 2018-09-11 at 11 23 35 pm" src="https://user-images.githubusercontent.com/8620059/45402139-c0ce8e00-b619-11e8-8d2a-d4aba2b0553c.png">

**Comment by aryehraber** [comment]
Can you confirm you are serving cached images directly as per: https://docs.statamic.com/tags/glide#serving-cached-images

**Comment by kodeine** [comment]
okay it was the cache issue, but now i am debugging it and it seems its not using the responsive image even though in html i see its using srcset. I opened the window for mobile and it loaded this image in network, ` /img/containers/main/img/desert.jpg/e81019f7751a2f374735cf6f5ca8568f.jpg 979w`

**Comment by kodeine** [comment]
Also, i added `data-attr="true"` and it shows the blur image but does not change after that, stays like that. 
<img width="800" alt="screen shot 2018-09-12 at 8 07 20 pm" src="https://user-images.githubusercontent.com/8620059/45461259-a05d0d00-b6c7-11e8-929b-925761f775ad.png">

**Comment by aryehraber** [comment]
> okay it was the cache issue, but now i am debugging it and it seems its not using the responsive image even though in html i see its using srcset. I opened the window for mobile and it loaded this image in network, /img/containers/main/img/desert.jpg/e81019f7751a2f374735cf6f5ca8568f.jpg 979w

After the addon has rendered the `img` tag with multiple srcset, the browser handles loading the most appropriate image automatically. Without more details it's hard to guess why the browser is loading a `979w` for mobile -- perhaps it's a large mobile screen size? 

As for the `data-attr="true"` option, this assumes you are using your own JS (or a lib) to handle lazy-loading — I'll clarify in the docs that this addon doesn't ship with JS.

**Comment by aryehraber** [comment]
Sorry, that’s not going to happen.

Using JS for lazy-loading is completely optional since the Addon works great without it (in fact, it was only added because it was a feature request).

More importantly, there are so many different approaches to achieve lazy-loading — I don’t want the Addon to force someone down a particular path.

Closing the issue since it doesn’t sound like I can help you any further.
